### ISSUE TITLE
Running on a device

### ISSUE THREAD

**Issue by craigcoles** [joltup/react-native-threads#15]
I am having issues getting Threads running on a device either in Development or in Release mode.

I have three files within `App/Workers/*.thread.js`. I am alerting within the Thread also for debugging purposes and it never appears when I run any three of these threads on a device.

Any ideas to where I am going wrong?

**Comment by Traviskn** [comment]
One challenging thing about threads is that they are in a completely separate and isolated environment.  This means that they have no direct access to the UI or the main thread's console log. Only the main react native process that created the threads can control the UI or log messages to the console. 

One way to debug a thread is to have it post a message to the main react native process using `self.postMessage('my message');`, and having the main react native process log or alert that message it receives in the `thread.onmessage` callback.  Another way is to use a debugging tool like Reactotron.  Threads can make network calls, so they can connect to Reactotron directly over the network and log debug messages.  Check out the example app to see how I use both debugging strategies: https://github.com/joltup/react-native-threads/tree/master/examples/SimpleExample

**Comment by craigcoles** [comment]
I have managed to get Threads setup and working correctly using the simulator on my mac, but when I build the app to an actual device, they just don't seem to run at all.

**Comment by craigcoles** [comment]
Apologies, it turns out that the code I was running inside the thread takes a considerable amount of time to process on a device, compared to when running on the simulator/computer.
