### ISSUE TITLE
Cannot find module "NativeModules"

### ISSUE THREAD

**Issue by runar-rkmedia** [joltup/react-native-threads#16]
Hi, I am having some trouble getting this plugin up and running with my project. I have basically copied the `worker.thread.js` and then instantiate the worker much like in the example in the readme:

```
import { Thread } from 'react-native-threads'

console.log('hello')
export const hintWorker = () => {
  // start a new react native JS process
  const thread = new Thread('worker.thread.js')

  // send a message, strings only
  thread.postMessage('hello')

  // listen for messages
  thread.onmessage = (message: any) => console.log(message)

  // stop the JS process
  thread.terminate()
}

```

However, when I run `hintWorker()`, I get an error-message, that it cannot find the NativeModules, which, as far as I know, is from React-Native. I guess it cannot find it inside the `worker.thread.js`-file.

```
    "react-native": "^0.51.0",
    "react-native-threads": "^0.0.10",
```

**Comment by Traviskn** [comment]
Hi @runar-rkmedia!  I'm curious to know, which version of React Native are you using, and are you running into this error on Android or iOS?

On Android you can run into this error if you do not make the necessary changes to your `MainApplication.java` file as described here in the README: https://github.com/joltup/react-native-threads#android

You need to pass RNThreadPackage a reference to mReactNativeHost in order for the thread to be able to access NativeModules.  Unfortunately the react-native link command isn't able to do this automatically

**Comment by runar-rkmedia** [comment]
I'm currently running react-native 0.51.0, and the error shows up on iOS, haven't tested on android yet.

**Comment by runar-rkmedia** [comment]
sorry, I must have forgotten to run `react-native link`. 

Thank you for your comment, it got me on the right track, and sorry if I am wasting your time here.

I guess this issue can be closed.

**Comment by runar-rkmedia** [comment]
After further inspection, this was caused by an issue with my babel-setup. This issue can, therefore, be closed.

**Comment by Traviskn** [comment]
Sounds good, I'm glad you were able to get it working!
