### ISSUE TITLE
Release APK unable to pickup thread js file and hence crashes

### ISSUE THREAD

**Issue by sja1n** [joltup/react-native-threads#24]
Hello again,
I trying to check the release version of my app after using Thread module in one of the pages and I have followed the steps to compile my `thread.js` and `support.js` file as per the command give accordingly and it generates the file as well, now when I open the page which is associated with this Thread module my app closes and tried removing it form the page and it works fine.

So probably I there might be some issue while building the bundle file.
PS: I have 2 thread worker files and I have compiled both the files.

Is there anything else I have to do for multiple files ?

And just FYI: in your simpleexample folder in `package.json` the command for build-thread-android has spacing in folder names hence does not work.

This is the [line](https://github.com/joltup/react-native-threads/blob/master/examples/SimpleExample/package.json#L9)

**Comment by Traviskn** [comment]
Hi @sja1n,

Thanks for pointing out the space in the simpleexampIe command, I'll need to remove that extra space!

Do you have a nested folder structure in your path to the thread files?  I've seen this type of issue before when the folder structure in the `android/app/src/main/assets/threads` and/or `ios` folders doesn't match the file path passed to the `Thread` constructor.

If that does not seem to be the problem, is there any more detail you could share with me? Perhaps a small app reproducing the issue?

**Comment by sja1n** [comment]
yes, I have kept the actual js file along with my other application pages, but for that I have given the appropriate path and it gets bundled correctly in `android/app/src/main/assets/threads`, 

it's, probably the path I might be giving wrongly in production app build
Right now I have given to thread might be wrong. Right now its like the normal file path relative to package.json `./src/Containers/Socket/Thread.js`.

Should I be giving it like `./android/app/src/main/assets/threads/thread.bundle` or something else?

**Comment by JoyHou** [comment]
I'm having the exact same problem, I'll keep watching this issue.
FYI, I am not an expert on Android, but I'm guessing does this issue related to gradle? I'm guessing gradle didn't read the bundle file I generated for it, instead, it generates its own bundle file then build the apk...

**Comment by Traviskn** [comment]
If the path you are passing to the thread constructor is like this: 
```javascript
new Thread('src/Containers/Socket/Thread.js')
```

Then the file path you'll need to place your built thread bundle in will need to look like this:
`./android/app/src/main/assets/threads/src/Containers/Socket/Thread.bundle`

This is documented in the README as well: https://github.com/joltup/react-native-threads#building-for-release

**Comment by JoyHou** [comment]
@Traviskn I passed the path to the thread constructor like this: 
`new Thread('../thread.js')`
(As you can see, the `thread.js` locates at upper level folder of current file)
And I create the file path for bundle like this: 
`./android/app/src/main/assets/threads/thread.bundle`
Is the path correct?

**Comment by Traviskn** [comment]
@JoyHou Although that path works in development mode thanks to the JavaScript packager, it will not work in production mode.  The correct path for production mode would be `new Thread('thread.js')`.  This is because in production mode we look in the `android/app/src/main/assets/threads` folder, and the path is relative to the root of that folder.  What I've needed to do in my projects is organize my files in such a way as to make the development and production paths match.

**Comment by sja1n** [comment]
Hi @Traviskn  thanks for pointing it out so while building for production release I gave the name as `Thread.jsbundle` instead of `Thread.bundle` and create the same path/folder structure as I have in source and it worked like a charm.
Thanks

**Comment by JoyHou** [comment]
@Traviskn Thank you so much! It now works perfectly!
