### ISSUE TITLE
Error Running Android SimpleExample

### ISSUE THREAD

**Issue by xiswar** [joltup/react-native-threads#27]
# Error Running Android SimpleExample

Steps to reproduce:
* Clone repo
* cd to ./examples/SimpleExample
* npm install
* react-native run-android

> :react-native-threads:processReleaseResources UP-TO-DATE
:react-native-threads:generateReleaseSources UP-TO-DATE
:react-native-threads:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:react-native-threads:compileReleaseJavaWithJavac
:react-native-threads:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/Rawsix/Documents/_Arbeit/Apps/react-native/wee-mobile/node_modules/react-native-threads/android/src/main/java/com/reactlibrary/ThreadBaseReactPackage.java:38: error: constructor AndroidInfoModule in class AndroidInfoModule cannot be applied to given types;
                new AndroidInfoModule(catalystApplicationContext),
                ^
  required: no arguments
  found: ReactApplicationContext
  reason: actual and formal argument lists differ in length
1 error
> :react-native-threads:compileReleaseJavaWithJavac FAILED
> 
> FAILURE: Build failed with an exception.

Did I miss something? Thanks for your help.

**Comment by xiswar** [comment]
Changing:

    new AndroidInfoModule(catalystApplicationContext)

to:

    new AndroidInfoModule(),

fixed the problem.

**Comment by Traviskn** [comment]
I think the issue is that we need to update the SimpleExample project's version of react native to the latest version

**Comment by alexlevy0** [comment]
+1 same issue here with react-native@55.4: 
```
error: constructor AndroidInfoModule in class AndroidInfoModule cannot be applied to given types;
required: ReactApplicationContext
found: no arguments
reason: actual and formal argument lists differ in length
```

**Comment by Traviskn** [comment]
The SimpleExample has been updated and should be working now on latest master

**Comment by joaom182** [comment]
On react-native 0.52 this causes an issue with DeviceInfo module

![screen shot 2018-07-25 at 18 04 00](https://user-images.githubusercontent.com/3612098/43229314-b9218e32-903a-11e8-8095-7fd4ada8319a.png)
