### ISSUE TITLE
`NativeModules` is empty

### ISSUE THREAD

**Issue by WesleydeSouza** [joltup/react-native-threads#31]
I'm trying to use this module together with [andpor/react-native-sqlite-storage](https://github.com/andpor/react-native-sqlite-storage), but something's preventing it from initializing correctly.

The error I could extract from the thread is:

```
TypeError: undefined is not an object (evaluating 'NativeModules["SQLite"][method]')
```

Seems to be related to [line 84 on `lib/sqlite.core.js`](https://github.com/andpor/react-native-sqlite-storage/blob/master/lib/sqlite.core.js#L84) that depends on the `NativeModule` bind for that module.

Is there a limitation on this kind of operation? I couldn't find any reference to `NativeModules` in the documentation.

I also found that `NativeModules` is an empty object inside a thread.

| Module                      | Version |
| --------------------------- | ------- |
| React Native                |  0.55.4 |
| react-native-threads        |  0.0.12 |
| react-native-sqlite-storage |   3.3.6 |

**Comment by Traviskn** [comment]
Hi @WesleydeSouza,

To use native packages such as `react-native-sqlite-storage` in a thread on Android, you will need to modify your `MainApplication.java` file as outlined in the [android section of the README](https://github.com/joltup/react-native-threads#android) 
```
To include additional native modules in your threads, pass them into the RNThreadPackage constructor after the mReactNativeHost like this: new RNThreadPackage(mReactNativeHost, new ExampleNativePackage(), new SQLitePackage())
```
On iOS the NativeModules object should not be empty.

**Comment by WesleydeSouza** [comment]
@Traviskn thanks for pointing that out!

I guess I'll open a PR and make that section a bit more prominent, or create a dedicated section referencing that somewhere in the README. 😄
