### ISSUE TITLE
Threads stop working no error message. 

### ISSUE THREAD

**Issue by ethantran** [joltup/react-native-threads#34]
Platform: Android 8.0.0
Device: Samsung Galaxy S9+
React Native Version: 0.55.4

Thanks for this library. I am using realm with this. Is there anyway to know when a thread stops working? I am experimenting realm database writes through a thread. I Json.stringify(data) to send the thread message with data it should store in realm. They work at first but then the onmessage handler stops working after a while. No error messages. If there is a way to know when it stops working, I could possibly check and recreate the thread before I postMessage. Or at the very least fix whatever is causing the thread to stop working.

**Comment by Traviskn** [comment]
If an exception is thrown from within a thread, then that thread will crash and become unreachable.

In my applications, I have implemented a small echo check, where I have the thread always echo back every command it is sent.  When the thread stops echoing back after a certain timeout threshold, then I know that the thread has probably crashed and I will call `terminate` on the thread and re-start it.

Another thing that may help is to wrap all your thread code in high level `try/catch` blocks to ensure you catch all exceptions.
