### ISSUE TITLE
undefined is not an object (evaluating ThreadManager.startThread)

### ISSUE THREAD

**Issue by joaom182** [joltup/react-native-threads#39]
i'm trying to install lib with `Mostly automatic installation` just running `react-native link react-native-threads`. I've cleaned up my app and rebuild, and: 

![screen shot 2018-07-16 at 11 57 23](https://user-images.githubusercontent.com/3612098/42765925-80fc2456-88ef-11e8-80d3-37fe6289e543.png)

So i can confirm that the lib has attached on Libraries folder:
![screen_shot_2018-07-16_at_12_02_01](https://user-images.githubusercontent.com/3612098/42766208-32305ad0-88f0-11e8-8ed4-4bea59b8db92.png)

But `libRNThread.a` is missing on `Link Binary With Libraries`.

So.. the command `react-native link react-native-threads` is missing to attach `libRNThread.a` on `Link Binary With Libraries`?

**Comment by Traviskn** [comment]
Interesting, which version of React Native are you running into this issue on?

**Comment by joaom182** [comment]
0.52.0

**Comment by Traviskn** [comment]
I'm not sure why this would have happened, if automatic linking isn't working in your environment I recommend following the manual linking instructions

**Comment by Dhirajbhujbal** [comment]
Even I also facing the same issue tried with both manual as well as an automatic linking same screen is displayed

**Comment by kalwaniyash** [comment]
Hey i am facing the same issue, i did automatic linking with react-native link and ThreadManager from NativeModules is not defined which is causing the ThreadManager.startThread of undefined error.

Any suggestion other than manual linking?
