### ISSUE TITLE
Native module is not installed correctly

### ISSUE THREAD

**Issue by joaom182** [joltup/react-native-threads#41]
Hello,

I'm trying to use [react-native-device-info](https://github.com/rebeccahughes/react-native-device-info) lib with `react-native-threads` on Android. In iOS works perfectly.

So I put on the `MainApplication.java` the dependency for `RNThreadPackage`

```java
new RNThreadPackage(
              mReactNativeHost,
              new RNDeviceInfo() <-- here
)
```

But throws this error:

![screen shot 2018-07-25 at 03 15 43](https://user-images.githubusercontent.com/3612098/43182915-a7d07f2a-8fb9-11e8-8c5d-fc16f2042a82.png)

When i try to use `react-native-device-info` on main regular thread of the react-native, works perfectly, so i think that the installation of this native module it's ok and has any issue or conflict with `react-native-threads`.

Somebody has any workaround or tip to help-me to investigate this issue?

**Comment by joaom182** [comment]
The issue is not related with `react-native-device-info` module, but the native module of react-native called `DeviceInfo`.

The exception comes from:

![screen shot 2018-07-25 at 18 04 00](https://user-images.githubusercontent.com/3612098/43227447-28efd210-9035-11e8-8244-c63074e9e723.png)

**Comment by Traviskn** [comment]
Is this issue only reproducible on react native 0.52? There have been many breaking changes between versions of react native, I don't think the current version of this library can support react native 0.52.

For future reference, it is nearly impossible to address issues like this without getting some basic information such as the version of react native you are running and the version of react-native-threads that you are using

**Comment by jinxac** [comment]
Also facing this on 0.48.3. Any suggestions?

**Comment by joaom182** [comment]
@jinxac try use my fork, has some changes that makes compatible with <= 0.52

[joaom182/react-native-threads](https://github.com/joaom182/react-native-threads)

**Comment by maggialejandro** [comment]
Same issue RN 0.55.4

**Comment by maggialejandro** [comment]
Same issue
RN 0.55.4
react-native-threads 0.0.14
