### ISSUE TITLE
Building for Release

### ISSUE THREAD

**Issue by demerzel21** [joltup/react-native-threads#43]
@Traviskn Having created the bundle of the worker using your **[Building for Release](https://github.com/joltup/react-native-threads#building-for-release)** instructions, with the default name `index.thread.js`, I still see it being pulled down from the dev server and not using the offline bundle, whereas `index.js` is not showing up and it is using the offline bundle `main.jsbundle`.

Does anything need to modified in `AppDelegate.m` to make mention of the thread webworker - `index.thread.jsbundle`?
```
// jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"..."
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
```
I see that is what causes the offline bundle to be used for the main `index.js`, but how does it know to use the offline bundle for the webworker `index.thread.js`?

**Comment by Traviskn** [comment]
I don't understand your question. This library has nothing to do with "offline". It simply allows you to run JS in a separate process. In development mode all your JS is loaded from the dev server, and in release mode all your JS will be loaded as file assets.

You don't need to modify your `AppDelegate.m` file, the thread bundle is loaded by a different mechanism when you call the `new Thread` constructor. You can follow the code path through these files: 
This is the JS code that executes when you call the JS Thread constructor: (Notice that it calls the native `ThreadManager` module)
https://github.com/joltup/react-native-threads/blob/master/js/Thread.js

This is the native Objective-C code that starts your thread bundle: https://github.com/joltup/react-native-threads/blob/master/ios/ThreadManager.m#L12
