### ISSUE TITLE
latest RN Android NativeModuleRegistryBuilder Changed

### ISSUE THREAD

**Issue by gaodeng** [joltup/react-native-threads#48]
https://github.com/facebook/react-native/commit/407e033b34b6afa0ea96ed72f16cd164d572e911#diff-3b4df9d6f8274463f67e764159059571

https://github.com/joltup/react-native-threads/blob/870257fcca5080c835deaed55aaadb8bfd5a3d89/android/src/main/java/com/reactlibrary/ReactContextBuilder.java#L72

**Comment by Traviskn** [comment]
Thanks for the heads up!

**Comment by Traviskn** [comment]
fixed by #50
