### ISSUE TITLE
installation error 

### ISSUE THREAD

**Issue by alainib** [joltup/react-native-threads#51]
Hello, i'm trying to install this package and run on Android .

I'm getting the following error now : 

		:react-native-threads:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
		     mypath\node_modules\react-native-threads\android\src\main\java\com\reactlibrary\ReactContextBuilder.java:72: error: constructor NativeModuleRegistryBuilder in class NativeModuleRegistryBuilder cannot be applied to given types;
				NativeModuleRegistryBuilder nativeRegistryBuilder = new NativeModuleRegistryBuilder(reactContext, this.instanceManager);
																	^
		  required: ReactApplicationContext,ReactInstanceManager,boolean
		  found: ReactApplicationContext,ReactInstanceManager
		  reason: actual and formal argument lists differ in length
		1 error
		:react-native-threads:compileReleaseJavaWithJavac FAILED

		FAILURE: Build failed with an exception.

		* What went wrong:
		Execution failed for task ':react-native-threads:compileReleaseJavaWithJavac'.
		> Compilation failed; see the compiler error output for details.

-  Package

    "react": "^16.5.2",
    "react-native": "^0.55.4",
    "react-native-threads": "0.0.15",

-  settings.gradle 

        include ':react-native-threads'
        project(':react-native-threads').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-threads/android')

-  build.gradle

       // in dependencies add : 
       compile project(':react-native-threads')

- MainApplication.java

        import com.reactlibrary.RNThreadPackage;
	
        public class MainApplication extends Application implements ReactApplication {

		private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
			@Override
			public boolean getUseDeveloperSupport() {
			  return BuildConfig.DEBUG;
			}

			@Override
			protected List<ReactPackage> getPackages() {
			  return Arrays.<ReactPackage>asList(
					new MainReactPackage(),
					new KDSocialShare(),
					new RNThreadPackage(mReactNativeHost),
					new ImageResizerPackage(),  
					new RNSensitiveInfoPackage(), 
					new RNFetchBlobPackage(), 
					new RNFSPackage(),
					new SnackbarPackage(),
					new MapsPackage(), 
					new PhotoViewPackage(), 
					new PickerPackage(), 
					new RNI18nPackage(),
					new VectorIconsPackage(), 
					new RCTExifPackage(), 
					new OpenSettingsPackage(),
					new GoogleAnalyticsBridgePackage());
			}
	   };

	  @Override
	  public ReactNativeHost getReactNativeHost() {
		return mReactNativeHost;
	  }

	  @Override
	  public void onCreate() {
		super.onCreate();
		SoLoader.init(this, /* native exopackage */ false);
	  }
	}

  any idea please ? thanks

**Comment by alainib** [comment]
EDIT :  
it compile with "react-native-threads" fixed at "0.0.13"

**Comment by lpongetti** [comment]
+1

**Comment by Traviskn** [comment]
nearly every update of react native breaks us on android, the internal APIs we are using are unfortunately not very stable. I'm glad to hear that react-native-threads 0.0.13 worked with your version of react-native. I have been able to get react-native-threads 0.0.15 working with react-native 0.57, and the latest 0.0.16 version works with react-native 0.58.5
