### ISSUE TITLE
RN0.58 Refactor NativeModuleRegistryBuilder remove addNativeModule

### ISSUE THREAD

**Issue by coldbess** [joltup/react-native-threads#58]
[NativeModuleRegistryBuilder](https://github.com/facebook/react-native/commit/875f70b8b691cd1fb3e802594bbd4461b9959751#diff-9dc4073d6038a2b98f9f36a9233be809l)

NativeModuleRegistryBuilder remove addNativeModule method 

[ReactContextBuilder line 137 error](https://github.com/joltup/react-native-threads/blob/master/android/src/main/java/com/reactlibrary/ReactContextBuilder.java)

**Comment by Vondry** [comment]
Is there any progress on this? 
Compiled with `"react-native": "^0.58.4"` and `"react-native-threads": "0.0.15"`.
Note that I also tried to downgrade react-native to `0.57.8`, but then threads did not compilel due to constructor parameters mismatch.

```
> Task :react-native-threads:compileDebugJavaWithJavac FAILED
/...project.../node_modules/react-native-threads/android/src/main/java/com/reactlibrary/ReactContextBuilder.java:137: error: cannot find symbol
                nativeRegistryBuilder.addNativeModule(nativeModule);
```

**Comment by Traviskn** [comment]
I'm working on a branch to try and fix this issue for react-native 0.58.5 compatibility, replaced `addNativeModule` with `processPackage` and got compilation working but I also run into the same error as @Vondry. Still trying to track it down, not sure why it says there is no implementation for HybridData as the class definitely exists 🤔

**Comment by Traviskn** [comment]
After a bit more research this appears to be a problem finding the C/C++ implementation of HybridData, we are perhaps missing some required call to an `SoLoader` method

**Comment by Traviskn** [comment]
Figured it out, we need to import a new version of the javascript executor factory from `com.facebook.react.jscexecutor.JSCExecutorFactory;`, PR incoming
