### ISSUE TITLE
Main thread is not receiving the message from thread.postMessage

### ISSUE THREAD

**Issue by banalola** [joltup/react-native-threads#65]
I can see the the method below from ThreadSElfModule.java being called but the message does not reach the onmessage of main application:
@ReactMethod
    public void postMessage(String data) {
        if (parentContext == null) { return; }

        parentContext.getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)
                .emit("Thread" + String.valueOf(threadId), data);
    }

Not sure where to go from here!!

**Comment by banalola** [comment]
I figured out what was the issue in my code.

**Comment by olifolkerd** [comment]
what was the issue in your code, we are having the same problem?

**Comment by felixSchl** [comment]
I am running into the same problem. @banalola or @olifolkerd were you able to figure this out?

**Comment by morganruffner** [comment]
I'm having the same issue, any suggestions? @banalola @olifolkerd @felixSchl
