### ISSUE TITLE
RN 0.61 TurboModuleRegistry ERROR IN ANDROID

### ISSUE THREAD

**Issue by skdev24** [joltup/react-native-threads#85]
When a thread bundle run it's gives a warning in android, it works perfectly in iOS.
```
const thread = new Thread('/thread.js');
```

![Screenshot_20191003-190318](https://user-images.githubusercontent.com/16745006/66131338-e35e8b00-e610-11e9-9b2d-684d2fb6860f.png)

"dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.2",
    "react-native-threads": "http://github.com/jhen0409/react-native-threads/tarball/rn61"
  }

**Comment by ihavenoface5** [comment]
#87

**Comment by Traviskn** [comment]
The linked fix is merged, but unfortunately android threads now take much longer to start. There is more we need to look into to get performance improved

**Comment by ihavenoface5** [comment]
Our performance issues were unrelated to react-native-threads. The latest master should be good to use on RN 61.
