### ISSUE TITLE
null is not an object (evaluating 'ThreadManager.startThread') (iOS)

### ISSUE THREAD

**Issue by jacobp100** [joltup/react-native-threads#86]
I'm in the process of upgrading an existing package from 0.59 to the latest (0.61.1)

I had this set up, and it used to work

I re-initialized my project via `react-native init` and copied the JS files back over, re-installed all the packages, so I don't think this is an issue with upgrading. I've updated all packages to the latest, so I'm using 0.0.016. I also have some other native packages (react-native-svg and @react-native-community/async storage), and they work without issue

With the autolinking, it compiles everything, but I get `TypeError: null is not an object (evaluating 'ThreadManager.startThread')`

I've tried linking this package the old way and manually adding it to XCode, but both of these seem to stop it even compiling

Any help would be hugely appreciated!

**Comment by skdev24** [comment]
Follow this => https://github.com/joltup/react-native-threads/issues/79#issuecomment-535380488

**Comment by jacobp100** [comment]
Thanks for that link! I'm not looking to set up Android just yet (but will do later). I'm just focusing on iOS for the moment

**Comment by jacobp100** [comment]
I updated to 0.0.17, and I no longer have this issue. I'll close this
