### ISSUE TITLE
null is not an object(evaluating"ThreadManager StartThread")

### ISSUE THREAD

**Issue by Libra11** [joltup/react-native-threads#88]
I got this error in RN 0.61.3  
IOS system
![image](https://libra321.oss-cn-huhehaote.aliyuncs.com/1C6A102F-931F-408F-9406-06DD6BC1CC57.png)

**Comment by Genhain** [comment]
Also experiencing this issue on the simulator

**Comment by dorthwein** [comment]
Sames

**Comment by ihavenoface5** [comment]
You will need manually link the library. See 
Duplicate of #86 #39 #79
